### PR TITLE
Added warning and coercion for missing trap column names

### PR DESCRIPTION
**Pull request by JosephReps**
Minor change plus  new support functions to rename / check `traps` argument in `read.acre()`

### CODE REVIEW

**Comment by b-steve** [comment]
Looks good. Just need to include a check that `traps` has two columns.

**Comment by JosephReps** [comment]
After some more testing, I've found that if the length of the traps list is larger than the max number of capture sessions, `read.acre` appears to work fine from the users perspective, but it results in an error when trying to `fit.acre`:

```
Error in stats::nlminb(obj$par, obj$fn, obj$gr) :
NA/NaN gradient evaluation
```
Due to the `create.capt` containing empty elements, for each of the `traps` elements without a corresponding session.

I've tried REALLY hard to get it to fix for the user and just give a warning, but it would require either a mjor restructure or some very messy code, not worth in my opinion, so instead I just added a stop and provide user with message:

```
Error in create.capt(captures = list(session = c(1L, 1L, 1L, 1L, 1L, 1L, :
    length of 'traps' is greater than the number of sessions in 'capt'.
``` 

Other minor changes for edge case fix aswell.

**Comment by b-steve** [comment]
Nice spotting!I think the error is the right thing to do: if the capture history list is a different length to the traps location list then it's impossible for us to guess which capture histories correspond to which trap locations.

A couple of questions:

1. What happens if the length of `traps` is smaller than the lenght of `capt`? Wouldn't that come with the same sorts of problems?
2. Do things work properly if there are no detections on one session? In this scenario we should have an "empty" `capt` component.

**Comment by JosephReps** [comment]
**With regards to 1:**

- If length of `traps` is 1, then we just assume we use the same traps for every capt session.
- If the length of `traps` is greater than 1, but less than the number of capt sessions, the following error occurs:

```
Error in create.capt(captures = list(session = c(1, 1, 1, 1, 1, 1, 1, :
The number of sessions based on "n.sessions" or "traps" can not match the captures data
```

**With regards to 2:**

Im not too sure about this. The following assertion is in the code:

```
if(!all(captures$session %in% seq(n.sessions))){
    stop('"session" must be assigned as successive positive integers begins from one.')
}
```

This definitley has me stumped though:

- **How we would represent an empty session in `capt`?** I think we would have to explicity note empty sessions, because for example if we ran 3 sessions, and the first two had detections whereas the last had none, the capt matrix would only have {1, 2} in the session column. Regardless, I think empty sessions are not currently supported, as when I try something like:

```
capt_empty_session_3$session
  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...
 [72] 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4
```

Which has sessions 1, 2, 4 in the `capt` data frame, `read.acre` creates this "empty" `capt` component, but we get the same error as for when there are too many traps:

```
fit.acre(empty_session.acre)
outer mgc:  NaN 
Error in stats::nlminb(obj$par, obj$fn, obj$gr) :
NA/NaN gradient evaluation
```

Is this something that needs fixing?

- **How come we can use this as "data"?** I understand that if we set out detectors, and we don't record any detections, we are kind of figuring out that the density might not be high in that area, but in the likelihood I thought we were only iterating over detections.

Sorry for the long post.

**Comment by b-steve** [comment]
Your instinct is correct that sessions without detections should affect the density estimate: if we put out lots of clusters of detectors but don't detect any animals at some of them, then that indicates there probably aren't many animals around.

The sessions without detections do indeed have a likelihood contribution! For each session, the likelihood contribution is f(n)*f(capt | n) (i.e., the probably of detecting n things, multiplied by the capture histories of those n things). For detectionless sessions, the last term disappears, and we're left with f(n). This is the Poisson PMF evaluated at n, with expectation equal to density multiplied by the ESA.

**Comment by b-steve** [comment]
I'm a little surprised that detectionless sessions aren't supported in acre (they certainly did work as expected in ascr). So yes, it's worth testing this out to see if it all works as it should, with comparisons to ascr if required.

**Comment by JosephReps** [comment]
After further testing I think I might've started to figure out the issue:

It appears detectionless sessions **are** currently supported. I've fit quite a few models with detectionless sessions. 

The problem occurs, I believe, when we have a moderate-or-greater number of detections, and then I try to add a detectionless session. The `TMB::MakeADFun(...)` works just fine, however, the `obj$fn()` returns inf, and `obj$gr()` returns an array of `NA`'s.

Seems to me like the likelihood is shooting of to inf as it is basically "impossible" to have all these detections, and then have a session where none are recorded? Which then causes `stats::nlminb(obj$par, obj$fn, obj$gr)` to error out. 

Does this seem like a reasonable explanation?

### Reprex:

**Working example: 5 sessions, ~5 detections each session, missing session 4**
```
# Set capt to have 5 sessions, missing session #4
empty_session <- mul_ses

# Smaller capt so as to not cause error
empty_session$capt <- mul_ses$capt[1:20, ]

# mul_ses already has sessions 1 and 2, so just add 3 and 5
empty_session$capt[1:5, ]$session <- 1
empty_session$capt[5:10, ]$session <- 2
empty_session$capt[10:15, ]$session <- 3
empty_session$capt[15:20, ]$session <- 5

# Just use one trap element for simplicity
empty_session$traps <- mul_ses$traps[[1]]

# Read and fit
empty_session.acre <- read.acre(empty_session$capt, empty_session$traps, control.mask = empty_session$control.mask)
empty_session.fit <- fit.acre(empty_session.acre)
```

**Error example: 5 sessions, ~20+ detections each session, missing session 4**

```
# mul_ses already has sessions 1 and 2, so just add 3 and 5
empty_session <- mul_ses
empty_session$capt[1:20, ]$session <- 3
empty_session$capt[95:109, ]$session <- 5

# Just use one trap element for simplicity
empty_session$traps <- mul_ses$traps[[1]]

# Read and fit
empty_session.acre <- read.acre(empty_session$capt, empty_session$traps, control.mask = empty_session$control.mask)
empty_session.fit <- fit.acre(empty_session.acre)
```

**Pull request closed without merging**
